[package]
name = "scope_gc"
version = "0.1.1"
edition = "2021"
description = "Scope GC"
keywords = ["gc"]
repository = "https://github.com/823984418/scope_gc"
license = "MIT OR Apache-2.0"

[dependencies]
